---
- hosts: 127.0.0.1
  connection: local
  roles:
    - role: gantsign.maven
      maven_version: '3.6.2'
    - role: nwoetzel.eclipse
      eclipse_distro: photon
    - role: geerlingguy.nodejs
      nodejs_version: "10.x"



    