---
- import_tasks: set_vars.yml
  tags: [eclipse]

- debug:
    var: eclipse_download_url

- import_tasks: download_to_master.yml
  when: eclipse_download_folder_remote is undefined 

- import_tasks: download_to_remote.yml
  when: eclipse_download_folder_remote is defined

- import_tasks: eclipse.yml
  tags: [eclipse]

- name: configure eclipse.ini
  import_tasks: eclipseini.yml
  tags: [eclipse]

- import_tasks: plugins.yml
  tags: [eclipse]

- import_tasks: config.yml
