---
# http://help.eclipse.org/juno/index.jsp?topic=/org.eclipse.platform.doc.isv/guide/p2_director.html
- name: set general plugin vars
  set_fact:
    plugin_name: "{{ item }}"
    plugin_tag: "ansible_install_plugin_{{ item }}"
    plugin_creates: "{{ eclipse_unpack_dir}}/features/{{ eclipse_plugin_dict[item].creates_feature }}*"
  tags: [eclipse_plugins]

- name: set plugin install uis and repositories
  set_fact:
    plugin_installIU: "{{ eclipse_plugin_dict[plugin_name].install_units | join(',') }}"
    plugin_repositories: "{{ ['http://download.eclipse.org/releases/' + eclipse_distro] + eclipse_plugin_dict[plugin_name].repositories }}"
  tags: [eclipse_plugins]

# all plugins
- name: Install eclipse plugins
  command: "{{ plugin_install_command }} \
    -repository {{ plugin_repositories | join(',') }} \
    -installIU {{ plugin_installIU }} \
    -tag {{ plugin_tag }}"
  args:
    creates: "{{ plugin_creates }}"
#  ignore_errors: True
  tags: [eclipse_plugins]
